import { TILE_COLOR_PALETTE } from './tileColorPalette.js';

/**
 * OfficeLayout.tiles is a flat array of these gids — one number per cell that
 * fully identifies "what's here", replacing the old TileType enum (a floor
 * pattern number, or WALL/VOID) PLUS the separate tileColorIndex array. Floor
 * and wall color are now baked into the gid itself, matching how a Tiled
 * tile layer works: one gid per cell, no per-cell property alongside it (see
 * office/tiled-schema design notes, and assets/tiled/floor-tileset.tsx /
 * wall-<N>-tileset.tsx, generated by generateTiledTilesets.ts, whose tile
 * layout this numbering is designed to align with).
 *
 * Layout of the gid space:
 *   0                                      → void (matches Tiled's own
 *                                             universal "empty cell" gid)
 *   1 .. MAX_FLOOR_PATTERNS*PALETTE_SIZE   → floor: pattern × color
 *   WALL_GID_BASE .. +PALETTE_SIZE-1       → wall: color (the rendered piece
 *                                             is derived from neighbors at
 *                                             render time, same as before —
 *                                             a wall gid only carries color)
 *
 * MAX_FLOOR_PATTERNS is a fixed ceiling (not the live getFloorPatternCount()),
 * generously above today's 11, so adding a new floor pattern PNG never shifts
 * WALL_GID_BASE and never invalidates gids already saved in a layout. Growing
 * TILE_COLOR_PALETTE itself, like adding a 12th floor pattern past this
 * ceiling, is a schema-breaking change (bump OfficeLayout.version) — same as
 * every other closed-set change in this file's history.
 */
export const VOID_GID = 0;
const MAX_FLOOR_PATTERNS = 32;
const PALETTE_SIZE = TILE_COLOR_PALETTE.length;
const FLOOR_GID_BASE = 1;
export const WALL_GID_BASE = FLOOR_GID_BASE + MAX_FLOOR_PATTERNS * PALETTE_SIZE;

export type TileKind = 'void' | 'floor' | 'wall';

export function tileKind(gid: number): TileKind {
  if (gid === VOID_GID) return 'void';
  return gid >= WALL_GID_BASE ? 'wall' : 'floor';
}

export function isVoid(gid: number): boolean {
  return gid === VOID_GID;
}

export function isWall(gid: number): boolean {
  return gid >= WALL_GID_BASE;
}

export function isFloor(gid: number): boolean {
  return gid > VOID_GID && gid < WALL_GID_BASE;
}

/** Build a floor gid — `pattern` is 1-based (matches the old TileType.FLOOR_N
 *  numbering and assets/floors/floor_<pattern-1>.png). */
export function floorGid(pattern: number, colorIndex: number): number {
  return FLOOR_GID_BASE + (pattern - 1) * PALETTE_SIZE + colorIndex;
}

export function wallGid(colorIndex: number): number {
  return WALL_GID_BASE + colorIndex;
}

/** The floor pattern number (1-based) a floor gid was built from — only
 *  meaningful when isFloor(gid). */
export function floorPatternOf(gid: number): number {
  return Math.floor((gid - FLOOR_GID_BASE) / PALETTE_SIZE) + 1;
}

/** The TILE_COLOR_PALETTE index a floor or wall gid was built from — null for
 *  void (nothing to tint). */
export function tileColorIndexOf(gid: number): number | null {
  if (isVoid(gid)) return null;
  if (isWall(gid)) return gid - WALL_GID_BASE;
  return (gid - FLOOR_GID_BASE) % PALETTE_SIZE;
}
