/**
 * Matrix chat panel: the emoji picker's curated set.
 *
 * A hand-picked ~300 rather than the full Unicode list: the picker is for the
 * common case (the OS emoji keyboard and plain pasting both still work for
 * everything else — the picker's search field takes a pasted emoji verbatim).
 * Each entry is `[emoji, keywords]`; keywords are lowercase, space-separated,
 * and matched by substring in the picker.
 */

export interface EmojiCategory {
  /** Section heading shown in the picker. */
  label: string;
  entries: readonly (readonly [string, string])[];
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    label: 'Smileys',
    entries: [
      ['😀', 'grinning happy smile face'],
      ['😃', 'smiley happy joy face'],
      ['😄', 'smile happy laugh face'],
      ['😁', 'grin beaming face'],
      ['😆', 'laughing squint haha face'],
      ['😅', 'sweat smile relief haha'],
      ['🤣', 'rofl rolling laughing lol'],
      ['😂', 'joy tears laughing lol cry'],
      ['🙂', 'slight smile fine face'],
      ['😉', 'wink face'],
      ['😊', 'blush smiling happy face'],
      ['😇', 'innocent halo angel'],
      ['🥰', 'love hearts adore face'],
      ['😍', 'heart eyes love face'],
      ['🤩', 'star struck excited wow'],
      ['😘', 'kiss blowing love face'],
      ['😋', 'yum tasty tongue face'],
      ['😛', 'tongue out playful'],
      ['😜', 'winking tongue silly'],
      ['🤪', 'zany crazy goofy face'],
      ['🤔', 'thinking hmm consider face'],
      ['🤨', 'raised eyebrow skeptic suspicious'],
      ['😐', 'neutral meh face'],
      ['😑', 'expressionless blank face'],
      ['🙄', 'eye roll ugh face'],
      ['😏', 'smirk sly face'],
      ['😬', 'grimace awkward face'],
      ['🤥', 'lying pinocchio nose'],
      ['😌', 'relieved calm face'],
      ['😴', 'sleeping zzz tired face'],
      ['🥱', 'yawning tired bored face'],
      ['😷', 'mask sick face'],
      ['🤒', 'thermometer sick fever face'],
      ['🤕', 'bandage hurt injured face'],
      ['🤢', 'nauseated sick green face'],
      ['🤮', 'vomit sick puke face'],
      ['🤧', 'sneezing tissue sick face'],
      ['🥵', 'hot heat sweating face'],
      ['🥶', 'cold freezing ice face'],
      ['😵', 'dizzy knocked out face'],
      ['🤯', 'exploding head mind blown'],
      ['🤠', 'cowboy hat yeehaw face'],
      ['🥳', 'party celebration birthday face'],
      ['😎', 'cool sunglasses face'],
      ['🤓', 'nerd glasses geek face'],
      ['🧐', 'monocle inspect fancy face'],
      ['😕', 'confused unsure face'],
      ['😟', 'worried concerned face'],
      ['🙁', 'frown sad slightly face'],
      ['😮', 'open mouth surprised wow'],
      ['😯', 'hushed surprised face'],
      ['😲', 'astonished shocked face'],
      ['😳', 'flushed embarrassed blush face'],
      ['🥺', 'pleading puppy eyes beg face'],
      ['😢', 'crying sad tear face'],
      ['😭', 'sobbing loud crying face'],
      ['😱', 'scream fear shocked face'],
      ['😖', 'confounded frustrated face'],
      ['😞', 'disappointed sad face'],
      ['😓', 'downcast sweat sad face'],
      ['😩', 'weary tired ugh face'],
      ['😤', 'triumph steam frustrated face'],
      ['😡', 'pouting angry rage mad face'],
      ['😠', 'angry mad face'],
      ['🤬', 'swearing cursing angry symbols'],
      ['💀', 'skull dead skeleton'],
      ['💩', 'poop pile poo'],
      ['🤡', 'clown face'],
      ['👻', 'ghost boo halloween'],
      ['👽', 'alien ufo space'],
      ['🤖', 'robot bot machine face'],
    ],
  },
  {
    label: 'Gestures & people',
    entries: [
      ['👋', 'wave hello goodbye hand'],
      ['🤚', 'raised back hand stop'],
      ['✋', 'raised hand high five stop'],
      ['🖖', 'vulcan spock salute hand'],
      ['👌', 'ok okay perfect hand'],
      ['🤌', 'pinched fingers italian chef'],
      ['✌️', 'victory peace hand'],
      ['🤞', 'crossed fingers luck hope'],
      ['🤟', 'love you gesture hand'],
      ['🤘', 'horns rock metal hand'],
      ['🤙', 'call me shaka hang loose'],
      ['👈', 'point left finger'],
      ['👉', 'point right finger'],
      ['👆', 'point up finger'],
      ['👇', 'point down finger'],
      ['☝️', 'index point up finger'],
      ['👍', 'thumbs up yes approve like'],
      ['👎', 'thumbs down no disapprove'],
      ['✊', 'raised fist power'],
      ['👊', 'fist bump punch'],
      ['👏', 'clap applause bravo hands'],
      ['🙌', 'raising hands hooray celebrate'],
      ['🤝', 'handshake deal agreement'],
      ['🙏', 'folded hands please thanks pray'],
      ['💪', 'flex muscle strong arm'],
      ['🖕', 'middle finger rude'],
      ['✍️', 'writing hand pen'],
      ['🤳', 'selfie phone hand'],
      ['👀', 'eyes look watching see'],
      ['👁️', 'eye look see'],
      ['🧠', 'brain smart mind'],
      ['🗣️', 'speaking head talk say'],
      ['👶', 'baby infant child'],
      ['🧒', 'child kid'],
      ['🧑', 'person adult'],
      ['👩', 'woman female'],
      ['👨', 'man male'],
      ['🧓', 'older person elder'],
      ['🤷', 'shrug dunno whatever person'],
      ['🤦', 'facepalm doh person'],
      ['🙇', 'bowing sorry thanks person'],
      ['🙋', 'raising hand question volunteer person'],
      ['💁', 'tipping hand sassy info person'],
      ['🧙', 'mage wizard magic'],
      ['🦸', 'superhero hero cape'],
      ['🏃', 'running runner person'],
      ['💃', 'dancing dancer woman'],
      ['🕺', 'dancing dancer man'],
    ],
  },
  {
    label: 'Hearts',
    entries: [
      ['❤️', 'red heart love'],
      ['🧡', 'orange heart love'],
      ['💛', 'yellow heart love'],
      ['💚', 'green heart love'],
      ['💙', 'blue heart love'],
      ['💜', 'purple heart love'],
      ['🖤', 'black heart love'],
      ['🤍', 'white heart love'],
      ['🤎', 'brown heart love'],
      ['💔', 'broken heart sad'],
      ['❤️‍🔥', 'heart on fire passion'],
      ['💕', 'two hearts love'],
      ['💞', 'revolving hearts love'],
      ['💓', 'beating heart love'],
      ['💗', 'growing heart love'],
      ['💖', 'sparkling heart love'],
      ['💘', 'heart arrow cupid love'],
      ['💝', 'heart ribbon gift love'],
    ],
  },
  {
    label: 'Animals & nature',
    entries: [
      ['🐶', 'dog puppy pet face'],
      ['🐱', 'cat kitten pet face'],
      ['🐭', 'mouse face'],
      ['🐹', 'hamster pet face'],
      ['🐰', 'rabbit bunny face'],
      ['🦊', 'fox face'],
      ['🐻', 'bear face'],
      ['🐼', 'panda face'],
      ['🐨', 'koala face'],
      ['🐯', 'tiger face'],
      ['🦁', 'lion face'],
      ['🐮', 'cow face'],
      ['🐷', 'pig face'],
      ['🐸', 'frog face'],
      ['🐵', 'monkey face'],
      ['🙈', 'see no evil monkey'],
      ['🙉', 'hear no evil monkey'],
      ['🙊', 'speak no evil monkey'],
      ['🐔', 'chicken hen'],
      ['🐧', 'penguin bird'],
      ['🐦', 'bird tweet'],
      ['🦆', 'duck bird'],
      ['🦉', 'owl bird wise'],
      ['🦄', 'unicorn horse magic'],
      ['🐝', 'bee honeybee insect'],
      ['🦋', 'butterfly insect'],
      ['🐌', 'snail slow'],
      ['🐢', 'turtle slow tortoise'],
      ['🐍', 'snake serpent'],
      ['🐙', 'octopus sea'],
      ['🦀', 'crab sea'],
      ['🐬', 'dolphin sea'],
      ['🐳', 'whale sea spouting'],
      ['🦈', 'shark sea'],
      ['🐉', 'dragon mythical'],
      ['🌵', 'cactus plant desert'],
      ['🎄', 'christmas tree holiday'],
      ['🌲', 'evergreen tree pine'],
      ['🌳', 'tree deciduous'],
      ['🍀', 'four leaf clover luck'],
      ['🌿', 'herb leaf plant'],
      ['🌸', 'cherry blossom flower spring'],
      ['🌹', 'rose flower'],
      ['🌻', 'sunflower flower'],
      ['🌈', 'rainbow weather pride'],
      ['⭐', 'star favorite'],
      ['🌟', 'glowing star sparkle'],
      ['✨', 'sparkles shiny magic'],
      ['⚡', 'lightning zap bolt electric'],
      ['🔥', 'fire flame hot lit'],
      ['💧', 'droplet water drop'],
      ['🌊', 'wave ocean water sea'],
      ['❄️', 'snowflake cold winter snow'],
      ['☀️', 'sun sunny weather'],
      ['🌙', 'crescent moon night'],
      ['☁️', 'cloud weather'],
      ['🌧️', 'rain cloud weather'],
      ['🌍', 'earth globe world europe africa'],
    ],
  },
  {
    label: 'Food & drink',
    entries: [
      ['🍏', 'green apple fruit'],
      ['🍎', 'red apple fruit'],
      ['🍌', 'banana fruit'],
      ['🍉', 'watermelon fruit'],
      ['🍇', 'grapes fruit'],
      ['🍓', 'strawberry fruit'],
      ['🍒', 'cherries fruit'],
      ['🍑', 'peach fruit'],
      ['🍍', 'pineapple fruit'],
      ['🥝', 'kiwi fruit'],
      ['🍋', 'lemon fruit sour'],
      ['🥑', 'avocado fruit'],
      ['🍅', 'tomato vegetable'],
      ['🌽', 'corn maize vegetable'],
      ['🥕', 'carrot vegetable'],
      ['🥔', 'potato vegetable'],
      ['🧄', 'garlic vegetable'],
      ['🍞', 'bread loaf'],
      ['🧀', 'cheese wedge'],
      ['🥚', 'egg'],
      ['🥓', 'bacon meat'],
      ['🍔', 'hamburger burger fast food'],
      ['🍟', 'french fries fast food'],
      ['🍕', 'pizza slice'],
      ['🌭', 'hot dog fast food'],
      ['🌮', 'taco mexican'],
      ['🌯', 'burrito wrap mexican'],
      ['🥗', 'salad green healthy'],
      ['🍝', 'spaghetti pasta'],
      ['🍜', 'ramen noodles steaming bowl'],
      ['🍣', 'sushi japanese'],
      ['🍦', 'ice cream soft serve'],
      ['🍩', 'doughnut donut sweet'],
      ['🍪', 'cookie sweet'],
      ['🎂', 'birthday cake celebration'],
      ['🍰', 'shortcake cake sweet'],
      ['🍫', 'chocolate bar sweet'],
      ['🍿', 'popcorn movie snack'],
      ['☕', 'coffee tea hot beverage'],
      ['🍵', 'tea green teacup'],
      ['🍺', 'beer mug drink'],
      ['🍻', 'beers cheers clinking mugs'],
      ['🥂', 'champagne cheers clinking glasses'],
      ['🍷', 'wine glass drink'],
      ['🍸', 'cocktail martini drink'],
      ['🥤', 'cup straw soda drink'],
    ],
  },
  {
    label: 'Activities',
    entries: [
      ['⚽', 'soccer football ball'],
      ['🏀', 'basketball ball'],
      ['🏈', 'american football ball'],
      ['⚾', 'baseball ball'],
      ['🎾', 'tennis ball'],
      ['🏐', 'volleyball ball'],
      ['🎱', 'billiards eight ball pool'],
      ['🏓', 'ping pong table tennis'],
      ['🏸', 'badminton racquet'],
      ['🥅', 'goal net'],
      ['⛳', 'golf flag hole'],
      ['🎣', 'fishing pole fish'],
      ['🥊', 'boxing glove'],
      ['🎽', 'running shirt sash'],
      ['🛹', 'skateboard'],
      ['⛷️', 'skier ski snow'],
      ['🏂', 'snowboarder snow'],
      ['🏋️', 'weight lifting gym'],
      ['🚴', 'biking cyclist bicycle'],
      ['🏆', 'trophy winner prize champion'],
      ['🥇', 'gold medal first place'],
      ['🥈', 'silver medal second place'],
      ['🥉', 'bronze medal third place'],
      ['🎫', 'ticket admission'],
      ['🎪', 'circus tent'],
      ['🎭', 'performing arts theater masks'],
      ['🎨', 'art palette paint'],
      ['🎬', 'clapper board movie film'],
      ['🎤', 'microphone sing karaoke'],
      ['🎧', 'headphones music'],
      ['🎼', 'musical score sheet music'],
      ['🎹', 'piano keyboard music'],
      ['🥁', 'drum music'],
      ['🎷', 'saxophone music'],
      ['🎺', 'trumpet music'],
      ['🎸', 'guitar music rock'],
      ['🎻', 'violin music'],
      ['🎲', 'game die dice'],
      ['♟️', 'chess pawn game'],
      ['🎯', 'direct hit dart bullseye target'],
      ['🎳', 'bowling ball pins'],
      ['🎮', 'video game controller gaming'],
      ['🕹️', 'joystick arcade game'],
      ['🧩', 'puzzle piece jigsaw'],
    ],
  },
  {
    label: 'Travel & places',
    entries: [
      ['🚗', 'car automobile red'],
      ['🚕', 'taxi cab'],
      ['🚌', 'bus'],
      ['🏎️', 'racing car fast'],
      ['🚓', 'police car'],
      ['🚑', 'ambulance'],
      ['🚒', 'fire engine truck'],
      ['🚚', 'delivery truck'],
      ['🚜', 'tractor farm'],
      ['🛴', 'kick scooter'],
      ['🚲', 'bicycle bike'],
      ['🏍️', 'motorcycle motorbike'],
      ['🚨', 'police light siren alarm'],
      ['🚀', 'rocket launch ship space'],
      ['🛸', 'flying saucer ufo'],
      ['🚁', 'helicopter'],
      ['✈️', 'airplane plane flight'],
      ['🚂', 'locomotive train steam'],
      ['🚆', 'train railway'],
      ['🚢', 'ship boat cruise'],
      ['⛵', 'sailboat sailing'],
      ['⚓', 'anchor ship'],
      ['🗺️', 'world map travel'],
      ['🏔️', 'snow capped mountain'],
      ['🌋', 'volcano eruption'],
      ['🏕️', 'camping tent'],
      ['🏖️', 'beach umbrella'],
      ['🏝️', 'desert island'],
      ['🏠', 'house home'],
      ['🏢', 'office building'],
      ['🏥', 'hospital'],
      ['🏰', 'castle'],
      ['🗽', 'statue of liberty new york'],
      ['🌉', 'bridge night'],
      ['🌆', 'cityscape dusk city'],
    ],
  },
  {
    label: 'Objects',
    entries: [
      ['⌚', 'watch time'],
      ['📱', 'mobile phone smartphone'],
      ['💻', 'laptop computer'],
      ['⌨️', 'keyboard computer'],
      ['🖥️', 'desktop computer monitor'],
      ['🖨️', 'printer'],
      ['🖱️', 'computer mouse'],
      ['💾', 'floppy disk save'],
      ['💿', 'optical disc cd'],
      ['📷', 'camera photo'],
      ['🎥', 'movie camera film'],
      ['📺', 'television tv'],
      ['📻', 'radio'],
      ['🔋', 'battery power'],
      ['🔌', 'electric plug power'],
      ['💡', 'light bulb idea'],
      ['🔦', 'flashlight torch'],
      ['🕯️', 'candle light'],
      ['🧯', 'fire extinguisher'],
      ['💸', 'money wings flying dollar'],
      ['💰', 'money bag dollar'],
      ['🪙', 'coin money'],
      ['💳', 'credit card money'],
      ['💎', 'gem diamond jewel'],
      ['⚖️', 'balance scale justice'],
      ['🔧', 'wrench tool'],
      ['🔨', 'hammer tool'],
      ['⚙️', 'gear settings cog'],
      ['🧲', 'magnet'],
      ['🔬', 'microscope science'],
      ['🔭', 'telescope astronomy'],
      ['📡', 'satellite antenna dish'],
      ['💊', 'pill medicine drug'],
      ['🩹', 'adhesive bandage plaster'],
      ['🧹', 'broom cleaning'],
      ['🧺', 'basket laundry'],
      ['🛒', 'shopping cart trolley'],
      ['🎁', 'gift present wrapped'],
      ['🎈', 'balloon party'],
      ['🎀', 'ribbon bow'],
      ['🪄', 'magic wand'],
      ['📦', 'package box parcel'],
      ['📬', 'mailbox mail letter'],
      ['📝', 'memo note pencil write'],
      ['📌', 'pushpin pin'],
      ['📎', 'paperclip attach'],
      ['✂️', 'scissors cut'],
      ['🔒', 'locked padlock secure'],
      ['🔓', 'unlocked open padlock'],
      ['🔑', 'key lock'],
      ['🗝️', 'old key'],
      ['📅', 'calendar date'],
      ['⏰', 'alarm clock time'],
      ['⏳', 'hourglass time waiting'],
      ['📚', 'books reading stack'],
      ['🔍', 'magnifying glass search'],
    ],
  },
  {
    label: 'Symbols',
    entries: [
      ['✅', 'check mark button done yes'],
      ['☑️', 'check box ballot done'],
      ['✔️', 'check mark done yes'],
      ['❌', 'cross mark x no wrong'],
      ['❎', 'cross mark button no'],
      ['➕', 'plus add'],
      ['➖', 'minus subtract'],
      ['➗', 'divide division'],
      ['✖️', 'multiply multiplication x'],
      ['❓', 'question mark'],
      ['❗', 'exclamation mark warning'],
      ['⚠️', 'warning caution sign'],
      ['🚫', 'prohibited no forbidden'],
      ['💯', 'hundred points perfect score'],
      ['🔞', 'no one under eighteen'],
      ['♻️', 'recycling symbol'],
      ['💤', 'zzz sleep'],
      ['💥', 'collision boom explosion'],
      ['💫', 'dizzy star'],
      ['💦', 'sweat droplets water'],
      ['💨', 'dashing away wind fast'],
      ['🕳️', 'hole'],
      ['💬', 'speech balloon chat message'],
      ['💭', 'thought balloon thinking'],
      ['🗨️', 'left speech bubble chat'],
      ['🔔', 'bell notification'],
      ['🔕', 'bell slash mute'],
      ['🎵', 'musical note music'],
      ['🎶', 'musical notes music'],
      ['➡️', 'right arrow'],
      ['⬅️', 'left arrow'],
      ['⬆️', 'up arrow'],
      ['⬇️', 'down arrow'],
      ['🔀', 'shuffle twisted arrows'],
      ['🔁', 'repeat loop arrows'],
      ['▶️', 'play button start'],
      ['⏸️', 'pause button'],
      ['⏹️', 'stop button'],
      ['🔴', 'red circle record'],
      ['🟢', 'green circle'],
      ['🟡', 'yellow circle'],
      ['🔵', 'blue circle'],
      ['🏁', 'chequered flag finish race'],
      ['🚩', 'triangular flag red warning'],
      ['🏳️', 'white flag surrender'],
      ['🏴‍☠️', 'pirate flag jolly roger'],
    ],
  },
];
