/**
 * System tray (status area) icon.
 *
 * Three jobs: a way back to a window you have minimised or sent away, an
 * at-a-glance answer to "is anyone waiting on me in chat", and the toggle for
 * whether the close button quits or parks the app here (default: quit — main
 * owns that preference and its persistence, this file only draws the checkbox).
 *
 * The unread count is pushed from the renderer over the `setUnreadCount` IPC
 * channel — the Matrix client already computes it for the ✉ button's badge
 * (`OfficeScene.setMatrixUnread`), and main has no Matrix session of its own to
 * ask. Main only decides how to *show* the number, so a renderer that has never
 * opened the chat panel simply never pushes one and the tray stays plain.
 *
 * Three separate signals carry the count, because no single one works
 * everywhere:
 *
 *  - **The icon.** The only one that works on every desktop, so it carries the
 *    binary fact (badge / no badge) rather than the number.
 *  - **The tooltip.** Reliable on Windows and macOS. On Linux it does reach the
 *    status area (Electron publishes it as the StatusNotifierItem `ToolTip`
 *    property — verified on the dbus item), but whether the panel draws it is
 *    entirely up to that panel, and several draw nothing.
 *  - **The menu's first line.** A disabled item spelling the count out in
 *    words. This is what makes the exact number reachable on a Linux panel that
 *    ignores tooltips, where a left click opens this menu anyway.
 *
 * Linux notes (this is the platform the app is actually run on):
 *  - Tray icons go through StatusNotifierItem/AppIndicator. Where no host is
 *    running (a bare tiling WM with no status bar applet) `new Tray()` still
 *    succeeds and simply shows nothing — which is why nothing below treats the
 *    tray as a required part of the boot path. `probeTrayHost()` is how far that
 *    can be checked, and it is not all the way; see its comment.
 *  - Vanilla GNOME draws no tray at all: the XEmbed area was removed in 3.26 and
 *    GNOME Shell implements no StatusNotifier host, so this needs the
 *    `appindicatorsupport@rgcjonas.gmail.com` extension. With that extension
 *    installed the icon is STILL dropped, and that one is upstream rather than
 *    ours: it fetches the item's properties on registration and Chromium answers
 *    `Get` on `IconName` with a D-Bus error rather than an empty string, so the
 *    extension logs "Impossible to get basic properties" and discards the item.
 *    Electron exposes no way to publish `IconName` (the icon goes out only as
 *    `IconPixmap`, which tolerant hosts — KDE, Quickshell, Waybar — fall back to),
 *    so there is nothing to fix on this side. Diagnose with:
 *      journalctl --user -b | grep -iE 'appindicator|statusnotifier'
 *  - `tray.on('click')` never fires under AppIndicator: a left click opens the
 *    context menu. "Show Pixel Agents" being a real menu item is therefore not
 *    a convenience, it is the only way back to the window on this platform.
 */
import { app, Menu, nativeImage, Tray } from 'electron';
import type { NativeImage } from 'electron';
import { execFile } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));

// desktop/src/tray.ts -> desktop/assets. Holds at runtime in both layouts: the
// compiled main lives at desktop/dist/tray.js in dev and at
// <app>/desktop/dist/tray.js when packaged, and electron-builder copies
// desktop/assets to <app>/desktop/assets to match (see electron-builder.yml).
const ASSETS = join(HERE, '..', 'assets');

// Pixel-art derived from the launcher icon; the "unread" variant is the same
// art with a red badge in its empty corner. Generated by
// desktop/build/gen-tray-icons.py. The @2x files are picked up automatically by
// nativeImage's HiDPI filename convention, so they are never named here.
const ICON_IDLE = join(ASSETS, 'tray.png');
const ICON_UNREAD = join(ASSETS, 'tray-unread.png');

/** Window control, supplied by main.ts — which owns the window's lifecycle
 *  (including re-creating it on macOS after the last one was closed). The tray
 *  deliberately holds no BrowserWindow reference of its own: it would go stale
 *  exactly when it matters, i.e. after a close/re-create. */
export interface TrayHooks {
  /** Un-minimise, un-hide, focus — creating the window if there is none. */
  reveal(): void;
  /** Send the window away without quitting. */
  hide(): void;
  /** Whether closing the window hides it here instead of quitting. Read at menu
   *  build time rather than cached, so main stays the single owner of the value
   *  (it is also the side that persists it and that the `close` handler asks). */
  closeToTray(): boolean;
  setCloseToTray(enabled: boolean): void;
  /** Run the interactive self-update check (native dialogs, owned by main). */
  checkForUpdates(): void;
  /** Ask the renderer to toggle the Mumble mic / deafen state. The tray never
   *  flips anything itself: its checkboxes are a display of what the renderer
   *  last reported (setTrayVoiceState), and the answer to a click comes back
   *  the same way. */
  toggleMic(): void;
  toggleDeafen(): void;
}

/** What the mic/deafen menu items mirror, pushed from the renderer over the
 *  `mumbleVoiceState` IPC channel (see mumble/service.ts). */
export interface TrayVoiceState {
  connected: boolean;
  micOn: boolean;
  deafened: boolean;
}

let tray: Tray | null = null;
let unread = 0;
let voice: TrayVoiceState = { connected: false, micOn: false, deafened: false };
let hooks: TrayHooks = {
  reveal: () => undefined,
  hide: () => undefined,
  closeToTray: () => false,
  setCloseToTray: () => undefined,
  checkForUpdates: () => undefined,
  toggleMic: () => undefined,
  toggleDeafen: () => undefined,
};

/** Decoded icons, kept because `render()` runs on every count change and the
 *  two images never change. `null` records "this asset does not load", so a
 *  missing file is not re-read from disk on every arriving message either. */
const iconCache = new Map<string, NativeImage | null>();

/** Loads a tray image, or returns null if the asset is missing/undecodable —
 *  a broken asset must degrade to "no tray", never to a failed launch. */
function loadIcon(path: string): NativeImage | null {
  const cached = iconCache.get(path);
  if (cached !== undefined) return cached;
  const image = nativeImage.createFromPath(path);
  const usable = image.isEmpty() ? null : image;
  iconCache.set(path, usable);
  return usable;
}

function countLabel(n: number): string {
  if (n <= 0) return 'No new messages';
  if (n === 1) return '1 new message';
  return `${n} new messages`;
}

function buildMenu(): Menu {
  return Menu.buildFromTemplate([
    // Not clickable — it is the display, not a control. On Linux this is the
    // only place the exact count appears.
    { label: countLabel(unread), enabled: false },
    { type: 'separator' },
    // The voice toggles, only while a Mumble session is up — exactly when the
    // panel's own buttons work. Checked means "off" for the mic (the state you
    // toggled INTO, matching the panel button lighting up red when muted) and
    // "silenced" for the sound. Wording matches those buttons' titles.
    ...(voice.connected
      ? [
          {
            label: 'Mute microphone',
            type: 'checkbox' as const,
            checked: !voice.micOn,
            click: () => hooks.toggleMic(),
          },
          {
            label: 'Silence everyone',
            type: 'checkbox' as const,
            checked: voice.deafened,
            click: () => hooks.toggleDeafen(),
          },
          { type: 'separator' as const },
        ]
      : []),
    { label: 'Show Pixel Agents', click: () => hooks.reveal() },
    { label: 'Hide to tray', click: () => hooks.hide() },
    { type: 'separator' },
    // The manual update path (the version gate is the on-demand one): useful
    // exactly here because a window hidden to tray has no UI to ask from.
    { label: 'Check for updates…', click: () => hooks.checkForUpdates() },
    { type: 'separator' },
    {
      // The setting lives here rather than in the app's own UI because this is
      // where its consequence lives: you can only turn it on from a tray you can
      // see, which is the same tray the window will be hiding into.
      label: 'Close button hides to tray',
      type: 'checkbox',
      checked: hooks.closeToTray(),
      click: (item) => {
        hooks.setCloseToTray(item.checked);
        // Rebuild so the menu still matches after main has normalised/stored the
        // value, rather than trusting the item's own optimistic tick.
        render();
      },
    },
    // Quits outright rather than closing the window: `window-all-closed`
    // already quits on Linux/Windows, on macOS a closed window would otherwise
    // leave the app (and this tray icon) running with no way out, and with
    // close-to-tray on a close does not quit at all.
    { label: 'Quit', click: () => app.quit() },
  ]);
}

/** Re-apply icon, tooltip and menu from the current count. */
function render(): void {
  if (!tray) return;
  const icon = loadIcon(unread > 0 ? ICON_UNREAD : ICON_IDLE);
  if (icon) tray.setImage(icon);
  const label = countLabel(unread);
  tray.setToolTip(unread > 0 ? `Pixel Agents — ${label}` : 'Pixel Agents');
  tray.setContextMenu(buildMenu());
}

/**
 * Create the tray icon. Call once, after `app.whenReady()`. Returns false when
 * the icon asset could not be loaded — the caller carries on regardless, since
 * the tray is an accessory to the window and never a prerequisite for it.
 */
export function createTray(trayHooks: TrayHooks): boolean {
  if (tray) return true;
  hooks = trayHooks;
  const icon = loadIcon(ICON_IDLE);
  if (!icon) return false;
  tray = new Tray(icon);
  // Windows/macOS: a left click is the expected way back to the window. Never
  // fires on Linux, where the same click opens the context menu instead.
  tray.on('click', () => hooks.reveal());
  render();
  return true;
}

/**
 * Whether anything on this desktop is in a position to DRAW a tray icon.
 *
 * `createTray` cannot answer this. It reports whether the icon asset decoded and
 * `new Tray()` returned, and on Linux both succeed against a session with no
 * status area at all — the item is published to D-Bus and nobody listens. So its
 * `true` has been standing in for "the user can see this", which it never meant.
 *
 * 'absent' is a firm answer and the only one worth acting on. 'unknown' covers
 * a session bus we could not ask (no `gdbus`, no bus, a timeout) and is
 * deliberately NOT treated as absence: on a working desktop that would switch
 * off a preference the user set on purpose.
 *
 * What this still cannot detect, and no probe can: a host that accepts the
 * registration and then discards the item. That is a real case, not a
 * hypothetical — gnome-shell-extension-appindicator reads the item's properties
 * on registration, Chromium's implementation answers `Get` on `IconName` with a
 * D-Bus error instead of an empty string (it publishes the icon only as
 * `IconPixmap`), and the extension logs "Impossible to get basic properties" and
 * drops it. The watcher still lists the item, so from here that desktop is
 * indistinguishable from a working one. Hence the close-to-tray default stays
 * "quit", and a second launch stays a way back to a hidden window.
 */
export type TrayHostStatus = 'present' | 'absent' | 'unknown';

/** Long enough for a busy session bus, short enough that nothing waits on it.
 *  The caller does not block on this either way. */
const PROBE_TIMEOUT_MS = 2000;

export async function probeTrayHost(): Promise<TrayHostStatus> {
  // Windows and macOS have a status area as part of the OS; there is no
  // equivalent question to ask, and no gdbus to ask it with.
  if (process.platform !== 'linux') return 'present';

  // Two separate facts. A watcher can be running with no panel attached to it
  // (a host crashed, an extension was disabled), which is exactly the state that
  // looks fine and draws nothing.
  const watcher = await gdbusCall([
    '--dest', 'org.freedesktop.DBus',
    '--object-path', '/org/freedesktop/DBus',
    '--method', 'org.freedesktop.DBus.NameHasOwner',
    'org.kde.StatusNotifierWatcher',
  ]);
  if (watcher === null) return 'unknown';
  if (!/\btrue\b/.test(watcher)) return 'absent';

  const host = await gdbusCall([
    '--dest', 'org.kde.StatusNotifierWatcher',
    '--object-path', '/StatusNotifierWatcher',
    '--method', 'org.freedesktop.DBus.Properties.Get',
    'org.kde.StatusNotifierWatcher', 'IsStatusNotifierHostRegistered',
  ]);
  // A watcher that does not implement the property is not evidence of absence —
  // it answered, which means something is there.
  if (host === null) return 'unknown';
  return /\btrue\b/.test(host) ? 'present' : 'absent';
}

/** One `gdbus call --session`, or null if it could not be asked. stdout only;
 *  `gdbus` prints a GVariant, so the caller matches on the literal `true`. */
function gdbusCall(args: string[]): Promise<string | null> {
  return new Promise((resolve) => {
    execFile(
      'gdbus',
      ['call', '--session', ...args],
      { timeout: PROBE_TIMEOUT_MS, windowsHide: true },
      (error, stdout) => resolve(error ? null : stdout),
    );
  });
}

/**
 * Report the renderer's Matrix unread count. Non-finite and negative values are
 * clamped to 0 rather than trusted: this number crosses the IPC boundary from
 * the less-trusted renderer, and it only ever drives a label and an icon
 * choice, so there is no case where rejecting the call beats normalising it.
 */
export function setTrayUnread(count: number): void {
  const next = Number.isFinite(count) ? Math.max(0, Math.floor(count)) : 0;
  if (next === unread) return;
  unread = next;
  render();
  // Dock badge on macOS. On Linux this needs the Unity launcher API, which most
  // desktops (including the Hyprland/StatusNotifier setup this was tested on)
  // do not provide — there the setter is simply dropped and the getter keeps
  // reporting 0. Free where it works, inert where it does not, so it is set
  // unconditionally rather than behind a platform branch that would have to
  // guess which Linux desktops qualify.
  app.badgeCount = unread;
}

/**
 * Mirror the renderer's Mumble state onto the menu's mic/deafen items. The
 * payload crosses IPC from the less-trusted renderer, but arrives here already
 * normalised to booleans (mumble/service.ts) and only ever draws two
 * checkboxes. Ignored when nothing changed — this is called from every state
 * emit, and rebuilding the menu closes it if it happens to be open.
 */
export function setTrayVoiceState(state: TrayVoiceState): void {
  if (
    state.connected === voice.connected &&
    state.micOn === voice.micOn &&
    state.deafened === voice.deafened
  ) {
    return;
  }
  voice = state;
  render();
}

export function destroyTray(): void {
  tray?.destroy();
  tray = null;
}
