/**
 * System tray (status area) icon.
 *
 * Three jobs: a way back to a window you have minimised or sent away, an
 * at-a-glance answer to "is anyone waiting on me in chat", and the toggle for
 * whether the close button quits or parks the app here (default: quit — main
 * owns that preference and its persistence, this file only draws the checkbox).
 *
 * The unread count is pushed from the renderer over the `setUnreadCount` IPC
 * channel — the Matrix client already computes it for the ✉ button's badge
 * (`OfficeScene.setMatrixUnread`), and main has no Matrix session of its own to
 * ask. Main only decides how to *show* the number, so a renderer that has never
 * opened the chat panel simply never pushes one and the tray stays plain.
 *
 * Three separate signals carry the count, because no single one works
 * everywhere:
 *
 *  - **The icon.** The only one that works on every desktop, so it carries the
 *    binary fact (badge / no badge) rather than the number.
 *  - **The tooltip.** Reliable on Windows and macOS. On Linux it does reach the
 *    status area (Electron publishes it as the StatusNotifierItem `ToolTip`
 *    property — verified on the dbus item), but whether the panel draws it is
 *    entirely up to that panel, and several draw nothing.
 *  - **The menu's first line.** A disabled item spelling the count out in
 *    words. This is what makes the exact number reachable on a Linux panel that
 *    ignores tooltips, where a left click opens this menu anyway.
 *
 * Linux notes (this is the platform the app is actually run on):
 *  - Tray icons go through StatusNotifierItem/AppIndicator. Where no host is
 *    running (a bare tiling WM with no status bar applet) `new Tray()` still
 *    succeeds and simply shows nothing — which is why nothing below treats the
 *    tray as a required part of the boot path.
 *  - `tray.on('click')` never fires under AppIndicator: a left click opens the
 *    context menu. "Show Pixel Agents" being a real menu item is therefore not
 *    a convenience, it is the only way back to the window on this platform.
 */
import { app, Menu, nativeImage, Tray } from 'electron';
import type { NativeImage } from 'electron';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));

// desktop/src/tray.ts -> desktop/assets. Holds at runtime in both layouts: the
// compiled main lives at desktop/dist/tray.js in dev and at
// <app>/desktop/dist/tray.js when packaged, and electron-builder copies
// desktop/assets to <app>/desktop/assets to match (see electron-builder.yml).
const ASSETS = join(HERE, '..', 'assets');

// Pixel-art derived from the launcher icon; the "unread" variant is the same
// art with a red badge in its empty corner. Generated by
// desktop/build/gen-tray-icons.py. The @2x files are picked up automatically by
// nativeImage's HiDPI filename convention, so they are never named here.
const ICON_IDLE = join(ASSETS, 'tray.png');
const ICON_UNREAD = join(ASSETS, 'tray-unread.png');

/** Window control, supplied by main.ts — which owns the window's lifecycle
 *  (including re-creating it on macOS after the last one was closed). The tray
 *  deliberately holds no BrowserWindow reference of its own: it would go stale
 *  exactly when it matters, i.e. after a close/re-create. */
export interface TrayHooks {
  /** Un-minimise, un-hide, focus — creating the window if there is none. */
  reveal(): void;
  /** Send the window away without quitting. */
  hide(): void;
  /** Whether closing the window hides it here instead of quitting. Read at menu
   *  build time rather than cached, so main stays the single owner of the value
   *  (it is also the side that persists it and that the `close` handler asks). */
  closeToTray(): boolean;
  setCloseToTray(enabled: boolean): void;
}

let tray: Tray | null = null;
let unread = 0;
let hooks: TrayHooks = {
  reveal: () => undefined,
  hide: () => undefined,
  closeToTray: () => false,
  setCloseToTray: () => undefined,
};

/** Decoded icons, kept because `render()` runs on every count change and the
 *  two images never change. `null` records "this asset does not load", so a
 *  missing file is not re-read from disk on every arriving message either. */
const iconCache = new Map<string, NativeImage | null>();

/** Loads a tray image, or returns null if the asset is missing/undecodable —
 *  a broken asset must degrade to "no tray", never to a failed launch. */
function loadIcon(path: string): NativeImage | null {
  const cached = iconCache.get(path);
  if (cached !== undefined) return cached;
  const image = nativeImage.createFromPath(path);
  const usable = image.isEmpty() ? null : image;
  iconCache.set(path, usable);
  return usable;
}

function countLabel(n: number): string {
  if (n <= 0) return 'No new messages';
  if (n === 1) return '1 new message';
  return `${n} new messages`;
}

function buildMenu(): Menu {
  return Menu.buildFromTemplate([
    // Not clickable — it is the display, not a control. On Linux this is the
    // only place the exact count appears.
    { label: countLabel(unread), enabled: false },
    { type: 'separator' },
    { label: 'Show Pixel Agents', click: () => hooks.reveal() },
    { label: 'Hide to tray', click: () => hooks.hide() },
    { type: 'separator' },
    {
      // The setting lives here rather than in the app's own UI because this is
      // where its consequence lives: you can only turn it on from a tray you can
      // see, which is the same tray the window will be hiding into.
      label: 'Close button hides to tray',
      type: 'checkbox',
      checked: hooks.closeToTray(),
      click: (item) => {
        hooks.setCloseToTray(item.checked);
        // Rebuild so the menu still matches after main has normalised/stored the
        // value, rather than trusting the item's own optimistic tick.
        render();
      },
    },
    // Quits outright rather than closing the window: `window-all-closed`
    // already quits on Linux/Windows, on macOS a closed window would otherwise
    // leave the app (and this tray icon) running with no way out, and with
    // close-to-tray on a close does not quit at all.
    { label: 'Quit', click: () => app.quit() },
  ]);
}

/** Re-apply icon, tooltip and menu from the current count. */
function render(): void {
  if (!tray) return;
  const icon = loadIcon(unread > 0 ? ICON_UNREAD : ICON_IDLE);
  if (icon) tray.setImage(icon);
  const label = countLabel(unread);
  tray.setToolTip(unread > 0 ? `Pixel Agents — ${label}` : 'Pixel Agents');
  tray.setContextMenu(buildMenu());
}

/**
 * Create the tray icon. Call once, after `app.whenReady()`. Returns false when
 * the icon asset could not be loaded — the caller carries on regardless, since
 * the tray is an accessory to the window and never a prerequisite for it.
 */
export function createTray(trayHooks: TrayHooks): boolean {
  if (tray) return true;
  hooks = trayHooks;
  const icon = loadIcon(ICON_IDLE);
  if (!icon) return false;
  tray = new Tray(icon);
  // Windows/macOS: a left click is the expected way back to the window. Never
  // fires on Linux, where the same click opens the context menu instead.
  tray.on('click', () => hooks.reveal());
  render();
  return true;
}

/**
 * Report the renderer's Matrix unread count. Non-finite and negative values are
 * clamped to 0 rather than trusted: this number crosses the IPC boundary from
 * the less-trusted renderer, and it only ever drives a label and an icon
 * choice, so there is no case where rejecting the call beats normalising it.
 */
export function setTrayUnread(count: number): void {
  const next = Number.isFinite(count) ? Math.max(0, Math.floor(count)) : 0;
  if (next === unread) return;
  unread = next;
  render();
  // Dock badge on macOS. On Linux this needs the Unity launcher API, which most
  // desktops (including the Hyprland/StatusNotifier setup this was tested on)
  // do not provide — there the setter is simply dropped and the getter keeps
  // reporting 0. Free where it works, inert where it does not, so it is set
  // unconditionally rather than behind a platform branch that would have to
  // guess which Linux desktops qualify.
  app.badgeCount = unread;
}

export function destroyTray(): void {
  tray?.destroy();
  tray = null;
}
